### ISSUE TITLE
implementation of scaler.joblib 

### ISSUE THREAD

**Issue by abuu94** [arunnthevapalan/diabetes-prediction-app#2]
Hi there... good job Brother.  i have learnt to build ML Project..  thank you for the article.     i follow all step of creating the project. but i did not see the step of creating scaler.joblib      

Please help

**Comment by arunnthevapalan** [comment]
Hey :) Thank you for your kind words. I'm glad it was helpful.
You can simply use `dump(scaler, '../models/scaler.joblib')` to create the file. I've updated the step on the [notebook.](https://github.com/arunnthevapalan/diabetes-prediction-app/blob/master/notebooks/diabetes_prediction_pipeline.ipynb)
Hope this helps!

**Comment by abuu94** [comment]
Thank you Arunn...     Nice to get a feedback from you...     i expect you
will open the door for me to communicate with you..  :)
